### ISSUE TITLE
Question: Sponsor a Feature

### ISSUE THREAD

**Issue by derycck** [trufanov-nok/scantailor-universal#114]
Dear Alexander. I know that in opensource volunteer projects, implementation priorities follow a natural rhythm depending on each developer's individual availability and passion.
But among a myriad of implementation requests, it is likely that for some of them, users would be willing to sponsor financially to prioritize their implementation.
I propose this idea because as I am a user, I know 2 dozen others who would be willing to pay collectively to see a certain feature implemented in Scantailor Universal.
What are your thoughts on this?

**Comment by trufanov-nok** [comment]
Hello,
I think ST Advanced had some donate option and it didn't help it. Universal is a much less popular project.
Accepting donations in a support of the certain features implementation is a risky thing. Some features I might don't want to implement... Some features might be not feasible to implement bcs it's too hard due to software architecture...
And I don't think funding will inspire me much anyway. DevOps / Code / Docs / Translation contribution would be more welcome.

**Comment by derycck** [comment]
thanks for the detailed answering. 🤝
