### ISSUE TITLE
Request: Support for Windows OS

### ISSUE THREAD

**Issue by rudolphos** [trufanov-nok/scantailor-universal#79]
I tried using this in WSL2 through VcXsrv but it was too slow.

**Comment by trufanov-nok** [comment]
It does support Windows. You may download windows binaries for ver 0.2.10 for now: https://github.com/trufanov-nok/scantailor-universal/releases/tag/0.2.10

I've just not rebuild windows binaries for v0.2.11 - because it's quite annoying process and the only significant change in 0.2.11 is experemental jpeg2000 input files support, and looks like people who asked for it are using linux. But eventually I'll made 0.2.11 windows binaries and for sure v0.3.0 will have windows version too.
